### [1/5] Inscription Sofia — SELLER
# Attendu : 201 Created + objet User avec id
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{sofiaEmail}}",
  "password": "{{password}}",
  "firstName": "Sofia",
  "lastName": "Kova",
  "roles": ["SELLER"]
}

###

### [2/5] Login Sofia — récupère JSESSIONID
# Attendu : 200 OK + cookie JSESSIONID dans l'onglet Cookies
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{sofiaEmail}}",
  "password": "{{password}}"
}

###

### [3/5] Inscription Théo — BUYER
# Attendu : 201 Created + objet User avec id
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{theoEmail}}",
  "password": "{{password}}",
  "firstName": "Théo",
  "lastName": "Martin",
  "roles": ["BUYER"]
}

###

### [4/5] Login Théo — récupère JSESSIONID
# Attendu : 200 OK + cookie JSESSIONID
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{theoEmail}}",
  "password": "{{password}}"
}

###

### [5/5] Logout
# Attendu : 200 OK ou 204 No Content
POST {{baseUrl}}/api/auth/logout